### ISSUE TITLE
Mécanique workflow

### ISSUE THREAD

**Issue by scux** [hands-agency/grandcentral#119]
Lorsque que j'ajoute une page à l'arborescence, au moment d'enregistrer ladite page, je me retrouve sur une page vide, la liste des éléments du workflow, dont je me fiche un peu.

Peut-on revenir à la liste de l'item concerné ?

**Comment by mvdandrieux** [comment]
La mécanique Workflow nécessite que nous changions l'attr status en live (bool). En cours.

**Comment by mvdandrieux** [comment]
https://github.com/hands-agency/grandcentral/commit/420219a0bfc3442437a174b6c6869bc1335a3768
