### ISSUE TITLE
Médiathèque : derniers points

### ISSUE THREAD

**Issue by scux** [hands-agency/grandcentral#122]
**Bugs**

- quand on upload une image via la zone prévue à cet effet, après l'upload, la liste n'est pas rafraichit
- dans l'ancienne version, après upload d'un fichier et rafraichissement de la liste, le nouvel élément ne pouvait pas être drag & drop et était donc inutilisable.
- ce cochon de slash dans l'url du media

**Ameliorations**

- pouvoir déplacer les fichiers dans les répertoires par drag&drop
- pouvoir supprimer les répertoires

**Comment by mvdandrieux** [comment]
- après l'upload, la liste n'est pas rafraichit + nouvel élément ne pouvait pas être drag & drop = 2f3df65
- ce cochon de slash dans l'url du media = je pige pas...

**Comment by scux** [comment]
@mvdandrieux 

Nouveau bug détecté sur la médiathèque.

Lorsque tu uploades plusieurs images en même temps, seule la dernière apparait (elles sont par contre toutes bien uploadées)

**Comment by mvdandrieux** [comment]
@scux 
https://github.com/hands-agency/grandcentral/commit/65e4e88f0e0abaf2ff845750d84a8a40c0d4eba2
