### ISSUE TITLE
Right et is_admin()

### ISSUE THREAD

**Issue by mvdandrieux** [hands-agency/grandcentral#131]
Nous avons un super champ de droits en back. Mais étrangement nous ne nous en servons pas. L'attr right de group n'est pas utilisé pas is_admin(), qui fait sa vérification sur l'attr admin... Une raison particulière ?

Si non il faut repasser sur les groupes...

**Comment by scux** [comment]
Dans mon souvenir, ce champ de droit n'était pas super du tout. Maintenant, j'ai peut-être loupé une étape...
Dans ma tête, je me suis arrêté à : "il faut faire du spécifique"
